export const DEGREE_TAGS = [
  "GRADUACAO",
  "MESTRADO",
  "MESTRADO-PROFISSIONALIZANTE",
  "DOUTORADO",
  "POS-DOUTORADO",
  "ESPECIALIZACAO",
  "APERFEICOAMENTO",
  "CURSO-TECNICO-PROFISSIONALIZANTE",
  "ENSINO-MEDIO-SEGUNDO-GRAU",
  "ENSINO-FUNDAMENTAL-PRIMEIRO-GRAU",
  "RESIDENCIA-MEDICA",
  "LIVRE-DOCENCIA",
] as const;

export type DegreeTag = (typeof DEGREE_TAGS)[number];
